version: '3'
services:
  zookeeper:
    image: qnib/plain-zookeeper
    ports:
      - "2181:2181"
  zkui:
    image: qnib/plain-zkui
    ports:
      - "9090:9090"
    environment:
      ZK_SERVER: "tasks.zookeeper"
  broker:
    image: qnib/plain-kafka:0.10.2.1
    ports:
      - "9092:9092"
    healthcheck:
      disable: true
    environment:
      KAFKA_BROKER_ID: '{{.Task.Slot}}'
      ZK_SERVERS: "tasks.zookeeper"
  burrow:
    image: qnib/plain-burrow
    ports:
      - "8000:8000"
